---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/beers":
    get:
      summary: Retrieves all beers
      tags:
      - Beers
      responses:
        '200':
          description: beers found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    image_url:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - name
                  - description
                  - created_at
                  - updated_at
        '500':
          description: internal server error
    post:
      summary: Creates a beer
      tags:
      - Beers
      parameters: []
      responses:
        '201':
          description: beer created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                image_url:
                  type: string
              required:
              - name
              - description
  "/beers/random":
    get:
      summary: Retrieves a random beer
      tags:
      - Beers
      responses:
        '200':
          description: random beer found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  image_url:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                - id
                - name
                - description
                - created_at
                - updated_at
        '404':
          description: not found
  "/beers/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    put:
      summary: Updates a beer
      tags:
      - Beers
      parameters: []
      responses:
        '200':
          description: beer updated
        '404':
          description: beer not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                image_url:
                  type: string
              required:
              - name
              - description
    delete:
      summary: Deletes a beer
      tags:
      - Beers
      responses:
        '204':
          description: beer deleted
        '404':
          description: beer not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:9292
