default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: user
  password: password
  host: 127.0.0.1
  port: 3307

development:
  <<: *default
  database: beer_api_development

test:
  <<: *default
  database: beer_api_test

production:
  <<: *default
  database: beer_api_production
  username: beer_api
  password: <%= ENV['BEER_API_DATABASE_PASSWORD'] %>